package ru.vityaman.tidb.api.method;

public enum Method {
    ALL, 
    INSERT, 
    UPDATE_BY_ID,
    CLEAR, 
    REMOVE_ENTRY_WITH_KEY,
    REMOVE_ALL_THOSE_LESS_THAN, 
    REMOVE_ALL_THOSE_KEY_LESS_THAN,
    ENTRIES_GROUPED_BY_CREATION_DATE, 
    COUNT_OF_ENTRIES_WITH_PERSON_GREATER_THAN,
    ENTRIES_WITH_TYPE_GREATER_THAN
}
